import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# Define primary branding colors
PRIMARY_COLOR = colors.HexColor("#1e1b4b")  # Dark Indigo
SECONDARY_COLOR = colors.HexColor("#4f46e5")  # Indigo Accent
TEXT_COLOR = colors.HexColor("#334155")  # Slate Gray
BG_LIGHT = colors.HexColor("#f8fafc")  # Warm Light Gray
BORDER_COLOR = colors.HexColor("#e2e8f0")  # Soft Gray Border

def create_pdf_report(filepath, report_title, summary_kpis, headers, rows):
    """
    Generates a professionally styled PDF report using ReportLab.
    
    :param filepath: Path to save the PDF.
    :param report_title: Title of the report (e.g. "Monthly Sales Report").
    :param summary_kpis: Dict of KPI keys and values (e.g. {"Total Sales": "$4,500"}).
    :param headers: List of string column headers for the main data table.
    :param rows: List of lists containing the table cell data.
    """
    # Create the document
    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )
    
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        textColor=PRIMARY_COLOR,
        spaceAfter=15
    )
    
    meta_style = ParagraphStyle(
        'ReportMeta',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        textColor=TEXT_COLOR,
        spaceAfter=25
    )
    
    h2_style = ParagraphStyle(
        'ReportH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        textColor=SECONDARY_COLOR,
        spaceBefore=15,
        spaceAfter=10
    )
    
    cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        textColor=TEXT_COLOR
    )

    cell_bold_style = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        textColor=PRIMARY_COLOR
    )

    # 1. Header Title
    story.append(Paragraph(report_title, title_style))
    
    # 2. Meta Info (Date, Generated By)
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta_text = f"<b>Generated on:</b> {current_time} | <b>Platform:</b> BusinessOS AI™ | <b>Status:</b> Official"
    story.append(Paragraph(meta_text, meta_style))
    
    # 3. KPI Dashboard Cards (represented as a grid table)
    story.append(Paragraph("Executive Summary", h2_style))
    
    kpi_data = []
    # Make groups of 2-3 KPIs for the row
    kpi_keys = list(summary_kpis.keys())
    kpi_row_keys = []
    kpi_row_vals = []
    
    for i, key in enumerate(kpi_keys):
        kpi_row_keys.append(f"<b>{key}</b>")
        kpi_row_vals.append(str(summary_kpis[key]))
        
        # Every 3 KPIs (or if last KPI), push to table data
        if (i + 1) % 3 == 0 or (i + 1) == len(kpi_keys):
            # Fill remaining columns if less than 3
            while len(kpi_row_keys) < 3:
                kpi_row_keys.append("")
                kpi_row_vals.append("")
                
            kpi_data.append(kpi_row_keys)
            kpi_data.append(kpi_row_vals)
            kpi_row_keys = []
            kpi_row_vals = []
            
    if kpi_data:
        kpi_table_data = [[Paragraph(cell, cell_style) for cell in row] for row in kpi_data]
        kpi_table = Table(kpi_table_data, colWidths=[170, 170, 170])
        kpi_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), BG_LIGHT),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ('BOX', (0,0), (-1,-1), 1, BORDER_COLOR),
            ('INNERGRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ]))
        story.append(kpi_table)
    
    story.append(Spacer(1, 20))
    
    # 4. Detailed Data Table
    story.append(Paragraph("Detailed Operations Log", h2_style))
    
    # Prepare table headers
    table_data = [[Paragraph(f"<b>{h}</b>", cell_bold_style) for h in headers]]
    
    # Prepare rows
    for r in rows:
        table_row = []
        for cell in r:
            table_row.append(Paragraph(str(cell), cell_style))
        table_data.append(table_row)
        
    # Build Table
    col_width = 510 / len(headers)  # evenly divide width of 510 pt
    data_table = Table(table_data, colWidths=[col_width] * len(headers))
    
    # Style Table
    t_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,1), (-1,-1), 6),
        ('BOTTOMPADDING', (0,1), (-1,-1), 6),
    ])
    
    # Add white text style specifically to headers
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        textColor=colors.white
    )
    table_data[0] = [Paragraph(f"<b>{h}</b>", header_style) for h in headers]
    
    # Alternating row colors
    for i in range(1, len(table_data)):
        if i % 2 == 0:
            t_style.add('BACKGROUND', (0, i), (-1, i), BG_LIGHT)
            
    data_table.setStyle(t_style)
    story.append(data_table)
    
    # 5. Footer / Signature Block
    story.append(Spacer(1, 40))
    footer_text = "CONFIDENTIAL: Internal Use Only. This report was generated autonomously by BusinessOS AI™ platform."
    story.append(Paragraph(f"<font color='#94a3b8' size='8'><i>{footer_text}</i></font>", cell_style))
    
    # Build PDF file
    doc.build(story)
